# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='image',
            field=models.ImageField(default='images/logo.png', upload_to='treasure_images'),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='img_url',
            field=models.CharField(max_length=255),
        ),
    ]
