# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20161110_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='image',
            field=models.ImageField(default='media/treasure_images/logo.png', upload_to='treasure_images'),
        ),
    ]
